wandb_version: 1
env:
  ports: 4
  bays: 10
  decks: 2
  cargo_classes: 6
  weight_classes: 3
  customer_classes: 2
  capacity:
  - 50
  TEU: 1000
  LCG_target: 0.95
  VCG_target: 1.05
  stability_difference: 0.1
  CI_target: 1.25
  hatch_overstowage_costs: 0.333333
  hatch_overstowage_mask: false
  long_crane_costs: 0.5
  episode_order: standard
  normalize_obs: true
  seed: 42
  utilization_rate_initial_demand: 1.1
  spot_percentage: 0.3
  iid_demand: true
  cv_demand: 0.5
  demand_uncertainty: true
  generalization: false
model:
  lr_end_factor: 0.5
  batch_size: 64
  init_dim: 8
  embed_dim: 128
  hidden_dim: 256
  num_encoder_layers: 1
  num_decoder_layers: 3
  num_heads: 4
  dropout_rate: 0.008972135903337364
  normalization: layer
  out_bias_pointer_attn: false
  temperature: 1.0
  critic_temperature: 1.0
  tanh_clipping: 0
  tanh_squashing: false
  scale_max: 1.0
  train_decode_type: continuous_sampling
  val_decode_type: continuous_projection
  test_decode_type: continuous_projection
  phase: train
  encoder_type: attention
  decoder_type: attention
  demand_aggregation: full
  logger: wandb
algorithm:
  type: ppo
  clip_range: 0.2
  ppo_epochs: 5
  mini_batch_size: 0.25
  normalize_adv: false
  normalize_return: false
  max_grad_norm: 0.5
  tau: 0.005
  kl_threshold: None
  kl_penalty_lambda: None
  gamma: 0.99
  gae_lambda: 0.95
  vf_lambda: 0.5
  entropy_lambda: 0.010071090711145904
  feasibility_lambda: 0.6773126513364854
  demand_lambda: 1.0
  stability_lambda: 1.0
  projection_lambda: 0.01
  adaptive_feasibility_lambda: false
training:
  lr: 0.00020407622212291503
  projection_type: weighted_scaling_policy_clipping
  projection_kwargs:
    alpha: 0.03216519289740723
    max_iter: 100
    project_per_port: false
  optimizer: Adam
  validation_freq: 0.2
  validation_patience: 2
  train_data_size: 72000000
  val_data_size: 5000
  test_data_size: 5000
testing:
  timestamp: '20250128_080908'
  num_episodes: 30
_wandb:
  python_version: 3.9.20
  cli_version: 0.17.7
  framework: torch
  is_jupyter_run: false
  is_kaggle_kernel: false
  start_time: 1738029304
  t:
    1:
    - 1
    - 50
    - 55
    - 105
    2:
    - 1
    - 50
    - 55
    - 105
    3:
    - 2
    - 3
    - 16
    - 23
    - 37
    4: 3.9.20
    5: 0.17.7
    8:
    - 5
    13: linux-x86_64
alpha:
  value: 0.03216519289740723
batch_size:
  value: 64
dropout_rate:
  value: 0.008972135903337364
entropy_lambda:
  value: 0.010071090711145904
feasibility_lambda:
  value: 0.6773126513364854
hidden_dim:
  value: 256
lr:
  value: 0.00020407622212291503
mini_batch_size:
  value: 0.25
num_decoder_layers:
  value: 3
num_encoder_layers:
  value: 1
num_heads:
  value: 4
ppo_epochs:
  value: 5
scale_max:
  value: 1.0
