algorithm:
  clip_range: 0.2
  demand_lambda: 1.0
  entropy_lambda: 0.010071090711145904
  feasibility_lambda: 0.00001773126513364854
  gae_lambda: 0.95
  gamma: 0.99
  max_grad_norm: 0.5
  mini_batch_size: 0.25
  ppo_epochs: 5
  stability_lambda: 1.0
  tau: 0.005
  type: sac # todo: sac lower violation than ppo -> tune other hyperparameters
  vf_lambda: 0.5
env:
  CI_target: 1.25
  LCG_target: 0.95
  TEU: 1000
  VCG_target: 1.05
  bays: 10
  blocks: 1
  capacity:
  - 50
  cargo_classes: 6
  customer_classes: 2
  cv_demand: 0.5
  decks: 2
  demand_uncertainty: true
  env_name: block_mpp #mpp
  episode_order: standard
  generalization: false
  hatch_overstowage_costs: 0.333333
  hatch_overstowage_mask: false
  block_stowage_mask: true
  iid_demand: true
  long_crane_costs: 0.5
  normalize_obs: true
  perturbation: 0.2
  ports: 4
  seed: 42
  spot_percentage: 0.3
  stability_difference: 0.1
  utilization_rate_initial_demand: 1.1 #1.5
  weight_classes: 3
model:
  batch_size: 64
  critic_temperature: 1.0
  decoder_type: attention
  dropout_rate: 0.008972135903337364
  embed_dim: 128
  encoder_type: attention
  hidden_dim: 128
  init_dim: 8
  logger: wandb
  lr_end_factor: 0.5
  normalization: layer
  num_decoder_layers: 3
  num_encoder_layers: 3
  num_heads: 8
  phase: train
  scale_max: 3.988627109442181
  tanh_clipping: 0
  tanh_squashing: false
  temperature: 0.1 #1146853501644833 #0.015
testing:
  num_episodes: 1
  folder: 'trial_20k'
  path: trained_models
  feasibility_recovery: false
training:
#  lr: 0.0003695184402239147
  lr: 0.00020407622212291503
  optimizer: Adam
  projection_kwargs:
    alpha: 0.027959542982510004
    delta: 0.0570646087054356
    max_iter: 200
#    alpha: 0.025
#    delta: 0.025
#    max_iter: 200
  projection_type: linear_violation # None, weighted_scaling_policy_clipping, linear_violation
  test_data_size: 5000
  train_data_size: 7200000 #72000000
  val_data_size: 5000
  validation_freq: 0.2
  validation_patience: 2
wandb_version: 1