method: bayes  # Or grid, random
metric:
  name: validation/total_violation  # Use the exact metric name from wandb.log()
  goal: minimize  # Since "violation" likely represents an error, we minimize it
run_cap: 100
parameters:
  feasibility_lambda:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_0:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_1:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_2:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_3:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_4:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_5:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_6:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_7:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_8:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_9:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_10:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_11:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_12:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_13:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_14:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_15:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_16:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_17:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_18:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_19:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_20:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_21:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_22:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_23:
    distribution: uniform
    min: 0.01
    max: 10
  lagrangian_multiplier_24:
    distribution: uniform
    min: 0.01
    max: 10