method: bayes
metric:
  name: val/total_profit_and_feas
  goal: maximize
run_cap: 100
parameters:
  feedforward_hidden:
    values: [128, 256,]
  num_encoder_layers:
    values: [1, 2, 3,]
  num_decoder_layers:
    values: [1, 2, 3,]
  num_heads:
    values: [4, 8,]
  ppo_epochs:
    values: [3, 5, 7]
  batch_size:
    values: [64, 128, 256] # 32, 64, 128 (each sample is a trajectory)
  mini_batch_size:
    values: [0.125, 0.25, 0.5, 1.0] # 8, 16, 32, 64, 128 (each sample is a trajectory)
  lr:
    min: 0.000001
    max: 0.001
  feasibility_lambda:
    min: 0.1
    max: 1.0