method: bayes
metric:
  name: validation.traj_return
  goal: maximize
run_cap: 100
parameters:
  lr:
    min: 0.000001
    max: 0.001
  temperature:
    min: 0.001
    max: 1.0
  scale_max:
    min: 0.25
    max: 10.0
  alpha:
    min: 0.0001 #0.001, 0.00001
    max: 0.1 #0.05, 0.005
  delta:
    min: 0.0001 #0.001, 0.00001
    max: 0.1 #0.001, 0.00001
  max_iter:
    min: 100
    max: 300
  feasibility_lambda:
    min: 0.0000001 #0000
    max: 0.001