method: bayes
metric:
  name: validation.traj_return
  goal: maximize
run_cap: 100
parameters:
#  lr:
#    min: 0.00001
#    max: 0.001
#  batch_size:
#    values: [64, 128, 256]
#  mini_batch_size:
#    values: [0.125, 0.25, 0.5,] # 1.0 causes issue with sampling
#  hidden_dim:
#    values: [128, 256, 512]
#  embed_dim:
#    values: [128, 256, ]
#  num_encoder_layers:
#    values: [2, 3, 4 ]
#  num_decoder_layers:
#    values: [2, 3, 4 ]
#  temperature:
#    min: 0.001
#    max: 1.0
#  scale_max:
#    min: 0.25
#    max: 10.0
#  alpha:
#    min: 0.0001
#    max: 0.1
#  delta:
#    min: 0.01
#    max: 0.1
#  max_iter:
#    min: 50
#    max: 300
#  scale:
#    min: 0.00001
#    max: 0.001
  feasibility_lambda:
    min: 0.00001
    max: 1.0